services:
  - type: cron
    name: trading-alert
    schedule: "*/15 * * * *"
    runtime: python
    buildCommand: ""
    startCommand: python trading.py
    envVars:
      - key: BOT_TOKEN
        value: TU_BOT_TOKEN
      - key: CHAT_ID
        value: "8073539508"
